version: '2'
services:
    jhipsterfirstapplication-app:
        image: jhipsterfirstapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@jhipsterfirstapplication-oracle:1521:jhipsterFirstApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 9090:9090
